server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${SPRING_CONFIG_IMPORT_URL:http://localhost:8888/}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:9080/realms/pmk/protocol/openid-connect/certs}

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8070/eureka/}

logging:
  level:
    com.conversion.pmk: DEBUG
    org.springframework.cloud.gateway: INFO
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
